# Use uma imagem base oficial do Node.js
FROM node:16-alpine

# Defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie o package.json e o package-lock.json
COPY package*.json ./

# Instale as dependências usando --legacy-peer-deps
RUN npm install --legacy-peer-deps

# Copie o restante do código da aplicação
COPY . .

# Comando para executar os testes
CMD ["npm", "test", "--", "--watchAll=false"]
